// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZMcuYKAz2dOn7n72aVyFBgt154CJTaw',
    appId: '1:53914079138:web:ed525de0c622eac85a2cfb',
    messagingSenderId: '53914079138',
    projectId: 'sophia-fb',
    authDomain: 'sophia-fb.firebaseapp.com',
    storageBucket: 'sophia-fb.appspot.com',
    measurementId: 'G-LVF059CH6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3j7c68Z9xkxVDmmS1xakJcQj5wO7ydjk',
    appId: '1:53914079138:android:7ac6245711d301145a2cfb',
    messagingSenderId: '53914079138',
    projectId: 'sophia-fb',
    storageBucket: 'sophia-fb.appspot.com',
  );
}
